# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2cb311b3c183a944dbee336cd0e97cd7c433b22703ad4848fe81e75469d7526a743c9f80081b684346ee3f8358b5ec4fd8700c9883352ec0299dc2d3ca23e09

test:
  secret_key_base: 7babd76408daaca179567bb757c5b7b708345ed4bbc72e6d865f4f689cfa7e34c3f08d5341f7f81a6e82be02855591aa4c8adb49038508671224e920d4b67945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
